displayName: Managing bookmarks
get:
    displayName: List bookmarks
    description: Lists bookmarked locations for the current user
    queryParameters:
        offset:
            description: The offset of the result set
            type: integer
            default: 0
        limit:
            description: The number of bookmarks returned
            type: integer
            default: 25
    headers:
        Accept:
            description: If set the list is returned in XML or JSON format
            example: |
                application/vnd.ez.api.BookmarkList+xml
                application/vnd.ez.api.BookmarkList+json
    responses:
        200:
            body:
                application/vnd.ez.api.BookmarkList+xml:
                    type: BookmarkList
                    example: !include examples/bookmark/GET/BookmarkList.xml.example
                application/vnd.ez.api.BookmarkList+json:
                    type: BookmarkList
                    example: !include examples/bookmark/GET/BookmarkList.json.example
        401:
            description: Error - the user is not authorized to list bookmarks
/{locationId}:
    post:
        displayName: Create bookmark
        description: Add given Location to bookmarks of current user
        responses:
            201:
                description: Created
            401:
                description: Error - the user is not authorized to given location
            404:
                description: Error - a given Location not exists
            409:
                description: Error - Location is already bookmarked
    head:
        displayName: Check if location is bookmarked
        description: Check if given Location is bookmarked by current user
        responses:
            200:
                description: OK - bookmarked
            401:
                description: Error - the user is not authorized to given location
            404:
                description: Error - a given Location not exists / is not bookmarked

    delete:
        displayName: Delete bookmark
        description: Delete given Location from bookmarks of current user
        responses:
            204:
                description: Deleted - no content
            401:
                description: Error - the user is not authorized to given location
            404:
                description: Error - a given Location not exists / is not bookmarked
