#%RAML 1.0
---
title: Ibexa REST API
baseUri: https://ezsystems.github.io/ezplatform-rest-reference
version: v3.3.2

/: !include ez-root.raml

/bookmark: !include ez-bookmark.raml

/content:
    displayName: Managing content
    /objects: !include ez-content-object.raml
    /objectstategroups: !include ez-objectstategroups.raml
    /locations:  !include ez-content-location.raml
    /views: !include ez-content-views.raml
    /sections: !include ez-content-section.raml
    /trash: !include ez-content-trash.raml
    /urlaliases: !include ez-content-urlaliases.raml
    /urlwildcards: !include ez-content-urlwildcards.raml
    /typegroups: !include ez-content-typegroups.raml
    /types: !include ez-content-types.raml

/calendar: !include ez-calendar.raml

/views: !include ez-views.raml

/user:
    displayName: Managing users
    /groups: !include ez-user-groups.raml
    /users: !include ez-user-users.raml
    /roles: !include ez-user-roles.raml
    /policies: !include ez-user-policies.raml
    /sessions: !include ez-user-sessions.raml
    /token: !include ez-user-token.raml

/services: !include ez-services.raml

/siso-rest:
    /basket:
        get:

        delete:

        /current:
            get:
                description: Gets current basket

            /party:
                /invoice:
                    patch:
                        description: Updates party information in the basket.

                /delivery:
                    patch:
                        description: Updates party information in the basket.

                /buyer:
                    patch:
                        description: Updates party information in the basket.

                /{partyType}:
                    patch:
                        description: Updates party information in the basket.


            /shippingmethod:
                patch:
                    description: Updates shipping information

            /paymentmethod:
                patch:
                    description: Updates payment information

            /voucher:
                patch:
                    description: Updates and checks voucher

            /lines:
                post:
                    description: Adds a product to a basket

        /copytocurrent/{id}:
            get:

        /createEmptyStored/{basketName}:
            get:
            post:

        /deleteLine/{basketId}/{lineId}:
            patch:

        /headers/{type}:
            get:
                description: Reads list of baskets. Returns wishlist/stored baskets.

        /update:
            post:
                description: Updates information in the basketline.

            /{id}/{mode}:
                post:

        /update-stored/{basketId}:
            post:

        /stores/lines:
            post:

    /basketline/{id}/{basketLineId}:
        delete:

    /checkout:
        /payment-methods:
            get:
                description: Gets list of payment methods.

        /shipping-methods:
            get:
                description: Gets list of payment methods.

        /update-referencenumber:
            patch:

        /update-remark:
            patch:

    /customer/addresses/shipping:
        get:
            description: Gets list of shipping addresses from customer.

    /customerprice:
        get:
        post:

    /common/check_sku_file:/{mode}:
        post:

    /country-selection:
        get:
            description: Gets list of payment methods.


types: !include ez-types.raml
